<?php

return [
    'migration' => [
        'fieldConversion' => [
            'string'               => '$table->string(\'column_name\', length)',
            'integer'              => '$table->integer(\'column_name\')',
            'text'                 => '$table->text(\'column_name\')',
            'date'                 => '$table->date(\'column_name\')',
            'tinyInteger'          => '$table->tinyInteger(\'column_name\')',
            'smallInteger'         => '$table->smallInteger(\'column_name\')',
            'mediumInteger'        => '$table->mediumInteger(\'column_name\')',
            'bigInteger'           => '$table->bigInteger(\'column_name\')',
            'decimal'              => '$table->decimal(\'column_name\', 8, 2)',
            'float'                => '$table->float(\'column_name\')',
            'double'               => '$table->double(\'column_name\')',
            'boolean'              => '$table->boolean(\'column_name\')',
            'bigIncrements'        => '$table->bigIncrements(\'column_name\')',
            'dateTime'             => '$table->dateTime(\'column_name\')',
            'timestamp'            => '$table->timestamp(\'column_name\')',
            'time'                 => '$table->time(\'column_name\')',
            'year'                 => '$table->year(\'column_name\')',
            'char'                 => '$table->char(\'column_name\', length)',
            'binary'               => '$table->binary(\'column_name\')',
            'enum'                 => '$table->enum(\'column_name\', $allowedValues)',
            'set'                  => '$table->set(\'column_name\', $allowedValues)',
            'geometry'             => '$table->geometry(\'column_name\')',
            'point'                => '$table->point(\'column_name\')',
            'linestring'           => '$table->linestring(\'column_name\')',
            'polygon'              => '$table->polygon(\'column_name\')',
            'multipoint'           => '$table->multipoint(\'column_name\')',
            'multilinestring'      => '$table->multilinestring(\'column_name\')',
            'multipolygon'         => '$table->multipolygon(\'column_name\')',
            'geometrycollection'   => '$table->geometrycollection(\'column_name\')',
            'json'                 => '$table->json(\'column_name\')',
        ],
        'default' => [
            'None'              => '',
            'As Defined:'      => '->default(\'value\')',
            'NULL'              => '->nullable()',
            'CURRENT_TIMESTAMP' => '->useCurrent()'
        ],
        'index' => [
            'PRIMARY'   => '->primary()',
            'UNIQUE'    => '->unique()',
            'INDEX'     => '->index()',
            'FULLTEXT'  => '->fullText()',
            'SPATIAL'   => '->spatialIndex()'
        ],
        'renameColumn' => '$table->renameColumn(\'current_value\', \'new_value\')',
    ],
    'selectOption' => [
        'type' => [
            'string',
            'integer',
            'text',
            'date',
            'tinyInteger',
            'smallInteger',
            'mediumInteger',
            'bigInteger',
            'decimal',
            'float',
            'double',
            'boolean',
            'bigIncrements',
            'dateTime',
            'timestamp',
            'time',
            'year',
            'char',
            'binary',
            'enum',
            'set',
            'geometry',
            'point',
            'linestring',
            'polygon',
            'multipoint',
            'multilinestring',
            'multipolygon',
            'geometrycollection',
            'json',
        ],
        'default' => [
            'None',
            'As Defined:',
            'NULL',
            'CURRENT_TIMESTAMP'
        ],
        'index' => [
            // 'PRIMARY',
            'UNIQUE',
            'INDEX',
            'FULLTEXT',
            'SPATIAL',
        ],
        'attributes' => [
            // 'BINARY',
            'UNSIGNED',
            // 'UNSIGNED ZEROFILL',
            // 'on UPDATE CURRENT_TIMESTAMP'
        ],
        'form_type' => [
            'string'               => 'input',
            'integer'              => 'input',
            'text'                 => 'textarea',
            'date'                 => 'input',
            'tinyInteger'          => 'input',
            'smallInteger'         => 'input',
            'mediumInteger'        => 'input',
            'bigInteger'           => 'input',
            'decimal'              => 'input',
            'float'                => 'input',
            'double'               => 'input',
            'boolean'              => 'input',
            'bigIncrements'        => 'input',
            'dateTime'             => 'input',
            'timestamp'            => 'input',
            'time'                 => 'input',
            'year'                 => 'input',
            'char'                 => 'input',
            'binary'               => 'input',
            'enum'                 => 'select',
            'set'                  => 'select',
            'geometry'             => 'input',
            'point'                => 'input',
            'linestring'           => 'input',
            'polygon'              => 'input',
            'multipoint'           => 'input',
            'multilinestring'      => 'input',
            'multipolygon'         => 'input',
            'geometrycollection'   => 'input',
            'json'                 => 'input',
        ],
        'form_input_type' => [
            'string'               => 'text',
            'integer'              => 'number',
            'text'                 => '',
            'date'                 => 'date',
            'tinyInteger'          => 'number',
            'smallInteger'         => 'number',
            'mediumInteger'        => 'number',
            'bigInteger'           => 'number',
            'decimal'              => 'number',
            'float'                => 'number',
            'double'               => 'number',
            'boolean'              => 'checkbox',
            'bigIncrements'        => 'number',
            'dateTime'             => 'datetime',
            'timestamp'            => 'datetime',
            'time'                 => 'time',
            'year'                 => 'number',
            'char'                 => 'text',
            'binary'               => 'file',
            'enum'                 => '',
            'set'                  => '',
            'geometry'             => 'text',
            'point'                => 'text',
            'linestring'           => 'text',
            'polygon'              => 'text',
            'multipoint'           => 'text',
            'multilinestring'      => 'text',
            'multipolygon'         => 'text',
            'geometrycollection'   => 'text',
            'json'                 => 'text',
        ]
    ]
];
